#!/bin/bash

rsync -rauh --delete ./ roku:ref12/

usage() {
    echo "Usage: $0 ( main | bench ) [ options ]"
    exit 1
}

if (( $# < 1 )); then
    usage
fi

if [[ $1 == 'check' ]]; then
    # Alias to ./roku main check
    exec "$0" main check
fi

( cd "$(dirname "$0")" && make clean >/dev/null )
( cd "$(dirname "$0")/bench" && make clean >/dev/null )
rsync --exclude=.* -ruh --delete "$(dirname "$0")" "roku:ref12/"

if [[ $1 == 'main' ]]; then
    ssh roku bash -v -s <<EOF
cd /home/daan/ref12
make ${*:2}
EOF
elif [[ $1 == 'bench' ]]; then
    ssh roku bash -v -s <<EOF
cd /home/daan/ref12/bench
make ${*:2}
EOF
else
    echo "Command $1 has no effect"
    echo
    usage
fi

exit 0
